# Site Settings
title: Joseph Renzi
description: A blog about mathematics, coding, and everything in between.
url: "https://josephrenzi.github.io"

# Custom layout - not using pre-built theme.
theme: minima
